contact: http://www.ucl.ac.uk/research-it-services/partner-with-us

defaults:
 -
  scope:
    path: ""
  values:
    layout: default
title: UCL Research Programming Hub
includeleftnav: True

findfast:
  title: Quick Links
  items:
  - link: events 
    text: Research Programming Technical Socials
  - link: affiliates
    text: Affiliated groups and institutes
  - link: friends
    text: Non-UCL organisations we like
